### PR TITLE
Fixed file references in r200 files

### PR DESCRIPTION
**Pull request by avitretiak**
compilation was failing because the files were wrongly referenced, added proper includes to fix this issue.

### CODE REVIEW

**Comment by Gamedev1909** [comment]
So my issues where not my fault sweet

**Comment by avitretiak** [comment]
Right, likely won't be used, but it will fail a regular make run as it will try to compile those files and fail.
Probably a non-issue but worth correcting anyways

**Comment by Gamedev1909** [comment]
^
make[4]: *** [Makefile:919: llvm/codegen/libclllvm_la-native.lo] Error 1
make[4]: Leaving directory '/home/gamedev/Downloads/mesa_mild_compatibility-master/pkgbuild/PKGBUILD/mesa64/src/mesa/src/gallium/state_trackers/clover'
make[3]: *** [Makefile:601: all-recursive] Error 1
make[3]: Leaving directory '/home/gamedev/Downloads/mesa_mild_compatibility-master/pkgbuild/PKGBUILD/mesa64/src/mesa/src/gallium'
make[2]: *** [Makefile:853: all-recursive] Error 1
make[2]: Leaving directory '/home/gamedev/Downloads/mesa_mild_compatibility-master/pkgbuild/PKGBUILD/mesa64/src/mesa/src'
make[1]: *** [Makefile:644: all] Error 2
make[1]: Leaving directory '/home/gamedev/Downloads/mesa_mild_compatibility-master/pkgbuild/PKGBUILD/mesa64/src/mesa/src'
make: *** [Makefile:649: all-recursive] Error 1
==> ERROR: A failure occurred in build().
    Aborting...   rip

**Comment by avitretiak** [comment]
Yeah, I've encountered those errors too sadly, they seem more complicated to fix than the one my commit does, I've got no idea how to frankly.

**Comment by mikakev1** [comment]
Hi, 
At the moment, I do not experience issue when building, I'm using a **genuine** archlinux.
[I do not use anymore the building script that has been unmaintened for a while]
I suspect this is related with your setup or the way you build it.

I'm using gcc 7.2 with glibc 2.26 (7.1 and 2.25 works perfectly)
```

--prefix=/usr \
               --sysconfdir=/etc \
               --with-dri-driverdir=/usr/lib/xorg/modules/dri \
               --with-gallium-drivers=i915,r300,r600,radeonsi,nouveau,svga,swrast,virgl \
               --with-dri-drivers=i915,i965,r200,radeon,nouveau,swrast \
               --with-platforms=x11,drm,wayland \
               --with-vulkan-drivers=intel,radeon \
               --enable-texture-float \
               --enable-gallium-osmesa \
               --enable-xa \
               --enable-nine \
               --disable-xvmc \
               --enable-vdpau \
               --enable-omx \
               --enable-opencl \
               --enable-opencl-icd \
               --enable-glx-tls \
               --enable-libglvnd
```

**Comment by mikakev1** [comment]
Thanks for your proposal, but I consider this is not an upstream bug or mine.

**Pull request closed without merging**
